declare interface IElevator_Elevator {
  db_id: string
  db_registCode: string // 注册代码
  db_innerNum: string // 电梯内部编号
  db_projectId: string // 所属项目id
  db_id_projectNum: string // 项目内编号
  db_elevType: string // 电梯类型:0直/1扶
  db_rescueCode: string // 96333救援识别码
  db_usePlaceCode: string // 使用性质(适用场所？)
  db_mapAddr: string // 地图地址
  db_mapLongi: string // 地图经度
  db_mapLati: string // 地图纬度
  db_brandId: string // 品牌id
  db_modelId: string // 型号id
  db_categoryCode: string // 电梯品种code
  db_manuId: string // 电梯生产商
  db_factoryCode: string // 出厂编号
  db_manuDate: string // 出厂日期
  db_installCompanyId: string // 安装单位
  db_installPassedDate: string // 初装验收合格日期
  db_reformCompanyId: string // 电梯改造单位
  db_reformDate: string // 电梯改造日期YYYY.MM.DD
  db_rise: string // 提升高度
  db_ratedSpeed: string // 额定速度
  db_topHeight: string // 顶层高度-直
  db_brandElseName: string // 电梯品牌名称
  db_modelElseName: string // 电梯型号名称
  db_pitDepth: string // 底坑深度-直
  db_floors: string // 楼层数-直
  db_stops: string // 停站数-直
  db_doors: string // 门数-直
  db_averageHeight: string // 平均层高
  db_ratedLoad: string // 额定载重量-直
  db_machineRoom: string // 是否有机房-直
  db_driveWay: string // 传动方式-直
  db_tractionRatio: string // 曳引比-直
  db_width: string // 宽度-扶
  db_angle: string // 倾斜角-扶
  db_length: string // 使用区长度-扶
  db_controlModelCode: string // 控制方式code
  db_iotIntime: string // 物联网入网时间
  db_maintModelCode: string // 维保模式code
  db_partInstIds: string // 配件实例清单,配件实例id以逗号拼接
  db_runMonitorPlanId: string // 运行监测方案id
  db_runMonitorDeviceId: string // 运行监测设备id
  db_videoMonitorPlanId: string // 视频监控方案id
  db_videoMonitorDeviceId: string // 视频监控设备id
  db_emergencyPlanId: string // 应急处置方案id
  db_emergencyDeviceId: string // 应急处置设备id
  db_originRunTimes: string // 原始运行次数
  db_originRunDuration: string // 原始运行时长
  db_originDuration: string // 原始自然时长
  db_originRunMileage: string // 原始运行里程
  db_originDoorTimes: string // 原始开关门次数
  db_upkeepInitTime: string // 保养初始时间（周期内的）
  db_initRunTimes: string // 距初始的运行次数(维保周期内的)
  db_initRunDuration: string // 距初始运行时长-小时(维保周期内的)
  db_initDuration: string // 距初始自然时长-小时(维保周期内的)
  db_initRunMileage: string // 距初始的运行里程(维保周期内的)
  db_initDoorTimes: string // 距初始的开关门次数(维保周期内的)
  db_lastMaintTime: string // 上次维保时间
  db_lastMaintRunTimes: string // 距上次维保运行次数
  db_lastMaintRunDuration: string // 距上次维保运行时长
  db_lastMaintDuration: string // 距上次维保自然时长
  db_lastMaintDoorTimes: string // 距上次维保开关门次数
  db_lastMaintRunMileage: string // 距上次维保运行里程
  db_lastRepairTime: string // 上次召修时间
  db_lastRepairRunTimes: string // 距上次召修运行次数
  db_lastRepairRunDuration: string // 距上次召修运行时长
  db_lastRepairDuration: string // 距上次召修自然时长
  db_lastRepairDoorTimes: string // 距上次召修开关门次数
  db_lastRepairRunMileage: string // 距上次召修运行里程
  db_lastEmergencyTime: string // 上次应急时间
  db_lastEmergencyRunTimes: string // 距上次应急运行次数
  db_lastEmergencyRunDuration: string // 距上次应急运行时长
  db_lastEmergencyDuration: string // 距上次应急自然时长
  db_lastEmergencyDoorTimes: string // 距上次应急开关门次数
  db_lastEmergencyRunMileage: string // 距上次应急运行里程
  db_totalRunTimes: string // 总运行次数
  db_totalRunDuration: string // 总运行时长
  db_totalDuration: string // 总自然时长
  db_totalRunMileage: string // 总运行里程
  db_totalDoorTimes: string // 总开关门次数
  db_maintTag: string // 已做的保养类型标识
  db_actualHalfMaintDayAndTimes: string // 实际半年保或阶段保天数次数，逗号拼接
  db_elevState: string // 电梯状态信息json
  db_latestInspectDate: string // 最近一次年检日期
  db_statisticInfo: string // 统计信息json
  db_rule: string // 电梯规则
  db_runUpdatetime: string // 运行数据更新时间
  db_runFeature: string // 电梯运行特性

  ui_projectName: string // 所属项目名称
  ui_usePlace: string // 适用场所
  ui_brandName: string // 品牌名称
  ui_modelName: string // 型号名称
  ui_category: string // 电梯品种
  ui_manuName: string // 电梯生产商名称
  ui_controlSys: string // 控制系统
  ui_manuDate: string // 出厂日期
  ui_installCompanyName: string // 安装单位名称
  ui_reformCompanyName: string // 改造单位名称
  ui_installPassedDate: string // 初装验收合格日期
  ui_reformDate: string // 电梯改造日期YYYY.MM.DD
  ui_iotIntime: string // 物联网入网时间
  ui_maintModel: string // 维保模式
  ui_runMonitorPlanName: string // 运行监测方案Name
  ui_videoMonitorPlanName: string // 视频监控方案Name
  ui_emergencyPlanName: string // 应急处置方案Name
  ui_upkeepInitTime: string // 保养初始时间
  ui_lastMaintTime: string // 上次维保时间
  ui_lastRepairTime: string // 上次召修时间
  ui_lastEmergencyTime: string // 上次应急时间
  ui_latestInspectDate: string // 最近一次年检日期
  ui_tractionRatio: string // 曳引比-直
  db_order: string // 排序

  ui_propMUserId: string // 物业经理id
  ui_propMUserPhone: string // 物业经理手机号
  ui_propPassUserId: string // 物业验收人id
  ui_propPassUserPhone: string // 物业验收人手机号
  ui_projectMUserId: string // 项目经理id
  ui_projectMUserPhone: string // 项目经理手机号
  ui_enginMUserId: string // 工程经理id
  ui_enginMUserPhone: string // 工程经理手机号
  ui_insuMUserId: string // 保险客户经理id
  ui_insuMUserPhone: string // 保险客户经理Phone
  ui_sceneUserId1: string // 现场联系人1(工程人员)
  ui_sceneUser1Phone: string // 现场联系人1手机号
  ui_sceneUserId2: string // 现场联系人2(工程人员)
  ui_sceneUser2Phone: string // 现场联系人2手机号
  ui_sceneUserId3: string // 现场联系人3(工程人员)
  ui_sceneUser3Phone: string // 现场联系人3手机号
  ui_sceneUserId4: string // 现场联系人4(工程人员)
  ui_sceneUser4Phone: string // 现场联系人4手机号

  ui_propMUserName: string // 物业经理名称
  ui_propPassUserName: string // 物业验收人名称
  ui_projectMUserName: string // 项目经理名称
  ui_enginMUserName: string // 工程经理名称
  ui_insuMUserName: string // 保险客户经理名称
  ui_sceneUserName1: string // 现场联系人1（工程人员)
  ui_sceneUserName2: string // 现场联系人2（工程人员)
  ui_sceneUserName3: string // 现场联系人3（工程人员)
  ui_sceneUserName4: string // 现场联系人4（工程人员)

  ui_runMonitorState: string // 运行监测状态
  ui_videoMonitorState: string // 视频监测状态
  ui_queryNullField: string // 运行为空查询条件
}
